// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyCulling(arg1) {
  return window['go']['main']['App']['ApplyCulling'](arg1);
}

export function BeginWatch(arg1) {
  return window['go']['main']['App']['BeginWatch'](arg1);
}

export function ChooseInputDir() {
  return window['go']['main']['App']['ChooseInputDir']();
}

export function ChooseOutputDir() {
  return window['go']['main']['App']['ChooseOutputDir']();
}

export function ClearRecents() {
  return window['go']['main']['App']['ClearRecents']();
}

export function Dedupe(arg1, arg2) {
  return window['go']['main']['App']['Dedupe'](arg1, arg2);
}

export function FormatPreview(arg1, arg2) {
  return window['go']['main']['App']['FormatPreview'](arg1, arg2);
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function HandleDrop(arg1) {
  return window['go']['main']['App']['HandleDrop'](arg1);
}

export function ListCullingPhotos() {
  return window['go']['main']['App']['ListCullingPhotos']();
}

export function MarkPhoto(arg1, arg2) {
  return window['go']['main']['App']['MarkPhoto'](arg1, arg2);
}

export function NotifyDesktop(arg1, arg2) {
  return window['go']['main']['App']['NotifyDesktop'](arg1, arg2);
}

export function OpenInFinder(arg1) {
  return window['go']['main']['App']['OpenInFinder'](arg1);
}

export function Organize(arg1) {
  return window['go']['main']['App']['Organize'](arg1);
}

export function PhotoData(arg1) {
  return window['go']['main']['App']['PhotoData'](arg1);
}

export function PhotoMeta(arg1) {
  return window['go']['main']['App']['PhotoMeta'](arg1);
}

export function ResetCullingMarks() {
  return window['go']['main']['App']['ResetCullingMarks']();
}

export function ResetPreferences() {
  return window['go']['main']['App']['ResetPreferences']();
}

export function SavePreferences(arg1) {
  return window['go']['main']['App']['SavePreferences'](arg1);
}

export function ScanPhotos(arg1) {
  return window['go']['main']['App']['ScanPhotos'](arg1);
}

export function ShowAbout() {
  return window['go']['main']['App']['ShowAbout']();
}

export function StopCurrentWatch() {
  return window['go']['main']['App']['StopCurrentWatch']();
}

export function StopOperation() {
  return window['go']['main']['App']['StopOperation']();
}
