// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BeginWatch(arg1) {
  return window['go']['main']['App']['BeginWatch'](arg1);
}

export function ChooseInputDir() {
  return window['go']['main']['App']['ChooseInputDir']();
}

export function ChooseOutputDir() {
  return window['go']['main']['App']['ChooseOutputDir']();
}

export function Dedupe(arg1, arg2) {
  return window['go']['main']['App']['Dedupe'](arg1, arg2);
}

export function GetPreferences() {
  return window['go']['main']['App']['GetPreferences']();
}

export function HandleDrop(arg1) {
  return window['go']['main']['App']['HandleDrop'](arg1);
}

export function OpenInFinder(arg1) {
  return window['go']['main']['App']['OpenInFinder'](arg1);
}

export function Organize(arg1) {
  return window['go']['main']['App']['Organize'](arg1);
}

export function SavePreferences(arg1) {
  return window['go']['main']['App']['SavePreferences'](arg1);
}

export function ScanPhotos(arg1) {
  return window['go']['main']['App']['ScanPhotos'](arg1);
}

export function StopCurrentWatch() {
  return window['go']['main']['App']['StopCurrentWatch']();
}

export function StopOperation() {
  return window['go']['main']['App']['StopOperation']();
}
